version: "3"

services:
  wiki-retrieval-service:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX}
    ports:
      - "8990:80"
    volumes:
      - ./app:/app
    deploy:
      resources:
        limits:
          memory: 1G

  wiki-qdrant-service:
    ports:
      - "8993:6333"
      - "8994:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    deploy:
      resources:
        limits:
          memory: 500M
